server:
  port: 8084

spring:
  application:
    name: trust-score-service

  data:
    redis:
      timeout: 2000ms

  kafka:
    consumer:
      group-id: trust-score-service
      auto-offset-reset: earliest
    producer:
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"

app:
  kafka:
    topics:
      joint-purchase-events: joint-purchase-events
      trust-score-events: trust-score-events